///<summary>
/// This class is auto-generated by Constants Generator script, if you want add new constants I recommend adding using the corresponding editor class.
/// Important: Not change the following constant values, these values will be match with the sames values in the scriptable object to work properly.
///</summary>
public static class AudioReferences
{
    public const string BACKGROUND_MUSIC = "Background music";
    public const string LETTER_SELECTED = "Letter selected";
    public const string WORD_SELECTED = "Word selected";
    public const string BUTTON_CLICKED = "Button clicked";
}